/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MemberAppRouteImport } from './routes/_member.app'
import { Route as MemberCategoriesRouteImport } from './routes/_member.categories'
import { Route as MemberPlansRouteImport } from './routes/_member.plans'
import { Route as MemberProfileRouteImport } from './routes/_member.profile'
import { Route as MemberWalletRouteImport } from './routes/_member.wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberAppRoute = MemberAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => MemberRoute,
} as any)
const MemberCategoriesRoute = MemberCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MemberRoute,
} as any)
const MemberPlansRoute = MemberPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberWalletRoute = MemberWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => MemberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/sign-in': typeof SignInRoute
  '/app': typeof MemberAppRoute
  '/categories': typeof MemberCategoriesRoute
  '/plans': typeof MemberPlansRoute
  '/profile': typeof MemberProfileRoute
  '/wallet': typeof MemberWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/sign-in': typeof SignInRoute
  '/app': typeof MemberAppRoute
  '/categories': typeof MemberCategoriesRoute
  '/plans': typeof MemberPlansRoute
  '/profile': typeof MemberProfileRoute
  '/wallet': typeof MemberWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_member': typeof MemberRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/sign-in': typeof SignInRoute
  '/_member/app': typeof MemberAppRoute
  '/_member/categories': typeof MemberCategoriesRoute
  '/_member/plans': typeof MemberPlansRoute
  '/_member/profile': typeof MemberProfileRoute
  '/_member/wallet': typeof MemberWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-account'
    | '/sign-in'
    | '/app'
    | '/categories'
    | '/plans'
    | '/profile'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-account'
    | '/sign-in'
    | '/app'
    | '/categories'
    | '/plans'
    | '/profile'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_member'
    | '/create-account'
    | '/sign-in'
    | '/_member/app'
    | '/_member/categories'
    | '/_member/plans'
    | '/_member/profile'
    | '/_member/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemberRoute: typeof MemberRouteWithChildren
  CreateAccountRoute: typeof CreateAccountRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/app': {
      id: '/_member/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof MemberAppRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/categories': {
      id: '/_member/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof MemberCategoriesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/plans': {
      id: '/_member/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof MemberPlansRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/profile': {
      id: '/_member/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/wallet': {
      id: '/_member/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof MemberWalletRouteImport
      parentRoute: typeof MemberRoute
    }
  }
}

interface MemberRouteChildren {
  MemberAppRoute: typeof MemberAppRoute
  MemberCategoriesRoute: typeof MemberCategoriesRoute
  MemberPlansRoute: typeof MemberPlansRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberWalletRoute: typeof MemberWalletRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAppRoute: MemberAppRoute,
  MemberCategoriesRoute: MemberCategoriesRoute,
  MemberPlansRoute: MemberPlansRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberWalletRoute: MemberWalletRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemberRoute: MemberRouteWithChildren,
  CreateAccountRoute: CreateAccountRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
